// PROJET SVELTE:REACT/my-cool-app/src/components/Quantity.jsx
import React from "react";

function Quantity({ tempQuantity, onUpdate }) {
  const increment = () => {
    onUpdate(tempQuantity + 1);
  };

  const decrement = () => {
    if (tempQuantity > 0) {
      onUpdate(tempQuantity - 1);
    }
  };

  return (
    <div>
      <button onClick={decrement}>-</button>
      <span>{tempQuantity}</span>
      <button onClick={increment}>+</button>
    </div>
 
 );
}

export default Quantity;

// PROJET SVELTE:REACT/project/src/lib/Quantity.svelte
<script>
  export let tempQuantity;
  export let onUpdate;

  const increment = () => {
    onUpdate(tempQuantity + 1);
  };

  const decrement = () => {
    if (tempQuantity > 0) {
      onUpdate(tempQuantity - 1);
    }
  };
</script>

<div>
  <button on:click={decrement}>-</button>
  <span>{tempQuantity}</span>
  <button on:click={increment}>+</button>
</div>
